#!/usr/bin/env bun
/**
 * generate-seed-sql.ts - Generate SQL INSERT statements from Effect-native SeedData.
 *
 * This script validates seed data completeness before generating SQL, ensuring
 * CI fails if any topic/level combination is missing.
 *
 * Usage:
 *   bun run apps/api/scripts/generate-seed-sql.ts > seed.sql
 *   # Or pipe directly to wrangler:
 *   bun run apps/api/scripts/generate-seed-sql.ts | wrangler d1 execute DB --remote --file=-
 *
 * Exit codes:
 *   0 - Success, SQL written to stdout
 *   1 - Validation failed (missing topic/level combinations)
 */
import { Effect } from "effect";
import * as Schema from "effect/Schema";
import { seedScenarios, validateSeedCompleteness } from "../src/seed/SeedData";
import { ScenarioTemplate } from "../src/domain/ScenarioTemplate";
import { hashSha256, stableJsonStringify } from "../src/domain/TemplateVersion";

const main = Effect.gen(function* () {
  // 1. Validate seed data completeness
  yield* validateSeedCompleteness;

  // 2. Generate SQL for each scenario
  const encode = Schema.encodeSync(ScenarioTemplate);

  console.log("-- Ensayo Quest Seed Data");
  console.log("-- Generated by: bun run apps/api/scripts/generate-seed-sql.ts");
  console.log(`-- Generated at: ${new Date().toISOString()}`);
  console.log("-- Topics: travel, food, work, hobbies");
  console.log("-- Levels: A1, A2, B1, B2");
  console.log("");

  // Seed user (for testing)
  console.log("-- Seed user");
  console.log(
    "INSERT OR IGNORE INTO users (id, handle, created_at) VALUES ('user_seed', 'seed', strftime('%s','now'));"
  );
  console.log("");

  // Seed scenarios
  console.log("-- Scenario templates");
  for (const seed of seedScenarios) {
    const encoded = encode(seed.template);
    const json = stableJsonStringify(encoded).replace(/'/g, "''");
    const templateVersion = yield* hashSha256(json);
    console.log(`INSERT OR REPLACE INTO scenario_templates`);
    console.log(`  (id, topic, level, region, register, template_version, template_json, created_at)`);
    console.log(`VALUES (`);
    console.log(`  '${seed.template.templateId}',`);
    console.log(`  '${seed.template.topic}',`);
    console.log(`  '${seed.template.level}',`);
    console.log(`  '${seed.region}',`);
    console.log(`  '${seed.register}',`);
    console.log(`  '${templateVersion}',`);
    console.log(`  '${json}',`);
    console.log(`  strftime('%s','now')`);
    console.log(`);`);
    console.log("");
  }
});

// Run and handle errors
Effect.runPromise(main).catch((error) => {
  console.error("Seed validation failed:", error);
  process.exit(1);
});
